create table if not exists public.customer_activity_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'purchase',
      'purchase_cancelled',
      'refund',
      'refund_cancelled'
    )
  ),
  receipt_number text not null references public.loyverse_receipts(receipt_number) on delete cascade,
  related_receipt_number text,
  title text not null,
  description text not null,
  amount numeric(14,2),
  points_delta bigint not null default 0,
  points_balance bigint,
  event_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  source_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_customer_activity_events_profile_event_at
  on public.customer_activity_events(profile_id, event_at desc);

create index if not exists idx_customer_activity_events_receipt
  on public.customer_activity_events(receipt_number);

alter table public.customer_activity_events enable row level security;

grant select on public.customer_activity_events to authenticated;

drop policy if exists "Clients can read own activity events" on public.customer_activity_events;
create policy "Clients can read own activity events"
on public.customer_activity_events
for select
to authenticated
using (profile_id = auth.uid());

drop policy if exists "Admins can read all activity events" on public.customer_activity_events;
create policy "Admins can read all activity events"
on public.customer_activity_events
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where public.admin_users.user_id = auth.uid()
  )
);

create or replace function public.record_customer_activity_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text;
  v_title text;
  v_description text;
  v_source_key text;
  v_event_at timestamptz;
  v_payment_names text[];
  v_payment jsonb;
  v_payment_name text;
  v_related text;
begin
  if new.profile_id is null then
    return new;
  end if;

  if new.receipt_type = 'SALE' and new.cancelled_at is null then
    v_type := 'purchase';
    v_title := 'Compra registrada';
    v_event_at := coalesce(new.receipt_date, new.created_at, new.updated_at, now());
    v_related := null;
  elsif new.receipt_type = 'SALE' and new.cancelled_at is not null then
    v_type := 'purchase_cancelled';
    v_title := 'Compra cancelada';
    v_event_at := coalesce(new.cancelled_at, new.updated_at, now());
    v_related := null;
  elsif new.receipt_type = 'REFUND' and new.cancelled_at is null then
    v_type := 'refund';
    v_title := 'Reembolso registrado';
    v_event_at := coalesce(new.receipt_date, new.created_at, new.updated_at, now());
    v_related := new.refund_for;
  elsif new.receipt_type = 'REFUND' and new.cancelled_at is not null then
    v_type := 'refund_cancelled';
    v_title := 'Reembolso cancelado';
    v_event_at := coalesce(new.cancelled_at, new.updated_at, now());
    v_related := new.refund_for;
  else
    return new;
  end if;

  v_source_key := 'receipt:' || new.receipt_number || ':activity:' || v_type;

  if jsonb_typeof(coalesce(new.payments, '[]'::jsonb)) = 'array' then
    for v_payment in
      select value from jsonb_array_elements(coalesce(new.payments, '[]'::jsonb))
    loop
      v_payment_name := nullif(trim(v_payment->>'name'), '');
      if v_payment_name is not null then
        v_payment_names := array_append(v_payment_names, v_payment_name);
      end if;
    end loop;
  end if;

  v_payment_names := (
    select array_agg(distinct x order by x)
    from unnest(coalesce(v_payment_names, array[]::text[])) as x
  );

  if v_type = 'purchase' then
    v_description := 'Ticket ' || new.receipt_number || ' · Compra por $' ||
      to_char(coalesce(new.total_money,0), 'FM999G999G999G990D00');
    if coalesce(array_length(v_payment_names,1),0) > 0 then
      v_description := v_description || ' · Pago con ' || array_to_string(v_payment_names, ' + ');
    end if;
    v_description := v_description || ' · 0 AP generados';
  elsif v_type = 'purchase_cancelled' then
    v_description := 'Ticket ' || new.receipt_number || ' · Compra cancelada por $' ||
      to_char(coalesce(new.total_money,0), 'FM999G999G999G990D00');
  elsif v_type = 'refund' then
    v_description := 'Ticket ' || new.receipt_number || ' · Reembolso por $' ||
      to_char(coalesce(new.total_money,0), 'FM999G999G999G990D00');
    if new.refund_for is not null then
      v_description := v_description || ' · Origen ' || new.refund_for;
    end if;
  else
    v_description := 'Ticket ' || new.receipt_number || ' · Cancelación de reembolso por $' ||
      to_char(coalesce(new.total_money,0), 'FM999G999G999G990D00');
    if new.refund_for is not null then
      v_description := v_description || ' · Origen ' || new.refund_for;
    end if;
  end if;

  insert into public.customer_activity_events (
    profile_id,
    event_type,
    receipt_number,
    related_receipt_number,
    title,
    description,
    amount,
    points_delta,
    points_balance,
    event_at,
    metadata,
    source_key
  )
  values (
    new.profile_id,
    v_type,
    new.receipt_number,
    v_related,
    v_title,
    v_description,
    new.total_money,
    0,
    new.points_balance,
    v_event_at,
    jsonb_build_object(
      'receipt_type', new.receipt_type,
      'refund_for', new.refund_for,
      'cancelled_at', new.cancelled_at,
      'payment_names', coalesce(v_payment_names, array[]::text[]),
      'total_money', coalesce(new.total_money,0),
      'points_earned', coalesce(new.points_earned,0),
      'points_deducted', coalesce(new.points_deducted,0)
    ),
    v_source_key
  )
  on conflict (source_key) do update
  set profile_id = excluded.profile_id,
      event_type = excluded.event_type,
      receipt_number = excluded.receipt_number,
      related_receipt_number = excluded.related_receipt_number,
      title = excluded.title,
      description = excluded.description,
      amount = excluded.amount,
      points_delta = excluded.points_delta,
      points_balance = coalesce(excluded.points_balance, public.customer_activity_events.points_balance),
      event_at = public.customer_activity_events.event_at,
      metadata = excluded.metadata,
      updated_at = now();

  return new;
end;
$$;

revoke all on function public.record_customer_activity_event() from public, anon, authenticated;
grant execute on function public.record_customer_activity_event() to service_role;

drop trigger if exists trg_record_customer_activity_event on public.loyverse_receipts;
create trigger trg_record_customer_activity_event
after insert or update on public.loyverse_receipts
for each row
execute function public.record_customer_activity_event();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='customer_activity_events'
  ) then
    alter publication supabase_realtime add table public.customer_activity_events;
  end if;
end
$$;

insert into public.customer_activity_events (
  profile_id,
  event_type,
  receipt_number,
  related_receipt_number,
  title,
  description,
  amount,
  points_delta,
  points_balance,
  event_at,
  metadata,
  source_key
)
select
  r.profile_id,
  'purchase',
  r.receipt_number,
  null,
  'Compra registrada',
  'Ticket ' || r.receipt_number || ' · Compra por $' ||
    to_char(coalesce(r.total_money,0), 'FM999G999G999G990D00') ||
    ' · Pago con TC · 0 AP generados',
  r.total_money,
  0,
  r.points_balance,
  coalesce(r.receipt_date, r.created_at, r.updated_at, now()),
  jsonb_build_object(
    'receipt_type', r.receipt_type,
    'refund_for', r.refund_for,
    'cancelled_at', r.cancelled_at,
    'payment_names', array['TC'],
    'total_money', coalesce(r.total_money,0),
    'points_earned', 0,
    'points_deducted', 0,
    'backfilled', true
  ),
  'receipt:' || r.receipt_number || ':activity:purchase'
from public.loyverse_receipts r
where r.receipt_number='5-1592'
  and r.profile_id is not null
on conflict (source_key) do update
set profile_id=excluded.profile_id,
    title=excluded.title,
    description=excluded.description,
    amount=excluded.amount,
    points_balance=excluded.points_balance,
    metadata=excluded.metadata,
    updated_at=now();
